'use client';
import {useState} from 'react';
export default function SettingsConsole(){
 const [saved,setSaved]=useState(false),[tab,setTab]=useState('Detection');const tabs=['Detection','Notifications','Response','Data'];
 return <section className="settings-layout"><aside className="settings-tabs">{tabs.map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{x}</button>)}</aside><div className="card settings-panel">
  {tab==='Detection'&&<><Heading title="Detection thresholds" text="Tune when coordinated traffic and application failures become an incident."/><div className="form-grid"><NumberField label="Warning HTTP 504 rate (%)" value="2"/><NumberField label="Critical HTTP 504 rate (%)" value="10"/><NumberField label="Emergency HTTP 504 rate (%)" value="30"/><NumberField label="Traffic baseline multiplier" value="5"/></div><Toggle title="Distributed crawler correlation" text="Correlate identity spread, unique paths, and traversal patterns." enabled/><Toggle title="Application failure detection" text="Watch PHP saturation, slow stacks, and availability degradation." enabled/></>}
  {tab==='Notifications'&&<><Heading title="Notification channels" text="Choose where Guardian.US sends incident alerts and recovery updates."/><Toggle title="WhatsApp alerts" text="Two-way response through AWS End User Messaging Social." enabled/><TextField label="WhatsApp sender ID" placeholder="Configured through deployment secrets"/><Toggle title="Email reports" text="Deliver bounded forensic summaries through Amazon SES." enabled/><TextField label="Notification recipients" placeholder="Configured through deployment secrets"/></>}
  {tab==='Response'&&<><Heading title="Safe response policy" text="All actions are allowlisted, time-bounded, audited, and revalidated by the local agent."/><Toggle title="Allow remote response requests" text="Operators may request predefined actions; arbitrary commands remain prohibited."/><Toggle title="Dry-run protection" text="Evaluate actions without changing firewall or web-server state." enabled/><div className="form-grid"><NumberField label="Default action TTL (seconds)" value="300"/><NumberField label="Maximum action TTL (seconds)" value="900"/></div></>}
  {tab==='Data'&&<><Heading title="Evidence and privacy" text="Keep incident evidence bounded and free of unnecessary personal data."/><div className="form-grid"><NumberField label="Evidence retention (days)" value="30"/><NumberField label="Maximum evidence lines" value="500"/></div><Toggle title="Remove query values" text="Retain parameter names while discarding values." enabled/><Toggle title="Fingerprint user agents" text="Store a stable fingerprint instead of raw user-agent strings." enabled/></>}
  <div className="settings-footer"><span className="muted small">Changes are preview-only until operator authentication is configured.</span><button className="button primary" onClick={()=>{setSaved(true);setTimeout(()=>setSaved(false),1800)}}>{saved?'Preview saved':'Save preview'}</button></div>
 </div></section>
}
function Heading({title,text}:{title:string;text:string}){return <div className="setting-heading"><h2>{title}</h2><p className="muted">{text}</p></div>}
function NumberField({label,value}:{label:string;value:string}){return <label className="field">{label}<input type="number" defaultValue={value}/></label>}
function TextField({label,placeholder}:{label:string;placeholder:string}){return <label className="field">{label}<input placeholder={placeholder}/></label>}
function Toggle({title,text,enabled=false}:{title:string;text:string;enabled?:boolean}){return <label className="toggle-row"><span><strong>{title}</strong><small>{text}</small></span><input type="checkbox" defaultChecked={enabled}/></label>}
